Update CI Builder

diff --git a/.github/workflows/ci_builder.yml b/.github/workflows/ci_builder.yml
--- a/.github/workflows/ci_builder.yml
+++ b/.github/workflows/ci_builder.yml
@@ -80,10 +80,30 @@ jobs:
                   make
                   cp server $GITHUB_WORKSPACE/release/
 
+            - name: Reduce updates size
+              run: |
+                  cd $GITHUB_WORKSPACE/release
+                  rm -rf learn/data/topics/Unity
+                  rm -rf learn/data/topics_math/Vids
+                  rm -rf learn/data/topics_math/Build
+                  rm -rf wallpapers
+
             - name: Compress out directory
               run: |
                   cd $GITHUB_WORKSPACE/release
                   zip -r $GITHUB_WORKSPACE/suvriddhi.zip .
+
+            - name: Final size check
+              run: |
+                  FILE_SIZE=$(stat -c %s "$GITHUB_WORKSPACE/suvriddhi.zip")
+                  MAX_SIZE=5242880
+
+                  if [ "$FILE_SIZE" -gt "$MAX_SIZE" ]; then
+                  echo "::error::File too large: $FILE_SIZE bytes (Max allowed is $MAX_SIZE bytes)"
+                  exit 1
+                  fi
+
+                  echo "Total size of suvriddhi.zip is within limits ($FILE_SIZE bytes)"
 
             - name: Create GitHub Release
               uses: softprops/action-gh-release@v1
